button_position = [{'x': 0.025, 'y': 0.8}, {'x': 0.275, 'y': 0.8}, {'x': 0.525, 'y': 0.8}, {'x': 0.775, 'y': 0.8},
                   {'x': 0.025, 'y': 0.675}, {'x': 0.275, 'y': 0.675}, {'x': 0.525, 'y': 0.675},
                   {'x': 0.775, 'y': 0.675}, {'x': 0.025, 'y': 0.55}, {'x': 0.275, 'y': 0.55},
                   {'x': 0.525, 'y': 0.55}, {'x': 0.775, 'y': 0.55}, {'x': 0.025, 'y': 0.425},
                   {'x': 0.275, 'y': 0.425}, {'x': 0.525, 'y': 0.425}, {'x': 0.775, 'y': 0.425},
                   {'x': 0.025, 'y': 0.3}, {'x': 0.275, 'y': 0.3}, {'x': 0.525, 'y': 0.3}, {'x': 0.775, 'y': 0.3},
                   {'x': 0.025, 'y': 0.175}, {'x': 0.275, 'y': 0.175}, {'x': 0.525, 'y': 0.175},
                   {'x': 0.775, 'y': 0.175}]

easy_images = ['images/puzzle_images/puzzle_easy_level/triangle.jpg',
               'images/puzzle_images/puzzle_easy_level/triangle.jpg',
               'images/puzzle_images/puzzle_easy_level/circle.jpg',
               'images/puzzle_images/puzzle_easy_level/circle.jpg',
               'images/puzzle_images/puzzle_easy_level/square.jpg',
               'images/puzzle_images/puzzle_easy_level/square.jpg',
               'images/puzzle_images/puzzle_easy_level/diamond.jpg',
               'images/puzzle_images/puzzle_easy_level/diamond.jpg',
               'images/puzzle_images/puzzle_easy_level/star.jpg',
               'images/puzzle_images/puzzle_easy_level/star.jpg',
               'images/puzzle_images/puzzle_easy_level/arrow.jpg',
               'images/puzzle_images/puzzle_easy_level/arrow.jpg',
               'images/puzzle_images/puzzle_easy_level/cloud.jpg',
               'images/puzzle_images/puzzle_easy_level/cloud.jpg',
               'images/puzzle_images/puzzle_easy_level/bubble.jpg',
               'images/puzzle_images/puzzle_easy_level/bubble.jpg',
               'images/puzzle_images/puzzle_easy_level/x.jpg',
               'images/puzzle_images/puzzle_easy_level/x.jpg',
               'images/puzzle_images/puzzle_easy_level/y.jpg',
               'images/puzzle_images/puzzle_easy_level/y.jpg',
               'images/puzzle_images/puzzle_easy_level/heart.jpg',
               'images/puzzle_images/puzzle_easy_level/heart.jpg',
               'images/puzzle_images/puzzle_easy_level/thunder.jpg',
               'images/puzzle_images/puzzle_easy_level/thunder.jpg']

medium_images = ['images/puzzle_images/puzzle_medium_level/1.jpg', 'images/puzzle_images/puzzle_medium_level/1.jpg',
                 'images/puzzle_images/puzzle_medium_level/2.jpg', 'images/puzzle_images/puzzle_medium_level/2.jpg',
                 'images/puzzle_images/puzzle_medium_level/3.jpg', 'images/puzzle_images/puzzle_medium_level/3.jpg',
                 'images/puzzle_images/puzzle_medium_level/4.jpg', 'images/puzzle_images/puzzle_medium_level/4.jpg',
                 'images/puzzle_images/puzzle_medium_level/5.jpg', 'images/puzzle_images/puzzle_medium_level/5.jpg',
                 'images/puzzle_images/puzzle_medium_level/6.jpg', 'images/puzzle_images/puzzle_medium_level/6.jpg',
                 'images/puzzle_images/puzzle_medium_level/7.jpg', 'images/puzzle_images/puzzle_medium_level/7.jpg',
                 'images/puzzle_images/puzzle_medium_level/8.jpg', 'images/puzzle_images/puzzle_medium_level/8.jpg',
                 'images/puzzle_images/puzzle_medium_level/9.jpg', 'images/puzzle_images/puzzle_medium_level/9.jpg',
                 'images/puzzle_images/puzzle_medium_level/10.jpg', 'images/puzzle_images/puzzle_medium_level/10.jpg',
                 'images/puzzle_images/puzzle_medium_level/11.jpg', 'images/puzzle_images/puzzle_medium_level/11.jpg',
                 'images/puzzle_images/puzzle_medium_level/12.jpg', 'images/puzzle_images/puzzle_medium_level/12.jpg']

hard_images = ['images/puzzle_images/puzzle_hard_level/1.jpg', 'images/puzzle_images/puzzle_hard_level/1.jpg',
                 'images/puzzle_images/puzzle_hard_level/2.jpg', 'images/puzzle_images/puzzle_hard_level/2.jpg',
                 'images/puzzle_images/puzzle_hard_level/3.jpg', 'images/puzzle_images/puzzle_hard_level/3.jpg',
                 'images/puzzle_images/puzzle_hard_level/4.jpg', 'images/puzzle_images/puzzle_hard_level/4.jpg',
                 'images/puzzle_images/puzzle_hard_level/5.jpg', 'images/puzzle_images/puzzle_hard_level/5.jpg',
                 'images/puzzle_images/puzzle_hard_level/6.jpg', 'images/puzzle_images/puzzle_hard_level/6.jpg',
                 'images/puzzle_images/puzzle_hard_level/7.jpg', 'images/puzzle_images/puzzle_hard_level/7.jpg',
                 'images/puzzle_images/puzzle_hard_level/8.jpg', 'images/puzzle_images/puzzle_hard_level/8.jpg',
                 'images/puzzle_images/puzzle_hard_level/9.jpg', 'images/puzzle_images/puzzle_hard_level/9.jpg',
                 'images/puzzle_images/puzzle_hard_level/10.jpg', 'images/puzzle_images/puzzle_hard_level/10.jpg',
                 'images/puzzle_images/puzzle_hard_level/11.jpg', 'images/puzzle_images/puzzle_hard_level/11.jpg',
                 'images/puzzle_images/puzzle_hard_level/12.jpg', 'images/puzzle_images/puzzle_hard_level/12.jpg']
